import Link from 'next/link';
import { tracks, careerReasons, videos, plan } from '../data/content';
export default function Home(){return <>
<section className="hero hero-home"><div className="container hero-grid"><div><div className="eyebrow">An UpForge.org learning initiative</div><h1>Become <span className="highlight">job-ready</span>, not just interview-ready.</h1><p>UpForge.in brings structured notes, quizzes, practical resources, project practice and AI interview simulations into one personal learning account — so you can learn, practice, explain and improve.</p><div className="actions"><Link className="btn primary big" href="/pricing">Get the ₹49 plan</Link><Link className="btn yellow big" href="/interview">Practice AI interview</Link></div><div className="trust-row"><span>✓ Personal account</span><span>✓ Saved progress</span><span>✓ 2 technical rounds</span></div></div><div className="hero-panel"><div className="hero-panel-top"><span className="tag">UPFORGE.IN</span><span className="live-dot">● Learning + AI</span></div><h3>One preparation loop</h3><div className="journey"><div><b>01 Learn</b><small>Notes, videos & resources</small></div><div><b>02 Test</b><small>Quizzes & project prompts</small></div><div><b>03 Simulate</b><small>AI interview follow-ups</small></div><div><b>04 Improve</b><small>Feedback & repeat practice</small></div></div><div className="hero-panel-foot">Built for students who want evidence of skill — not just a certificate.</div></div></div></section>
<section className="section"><div className="container"><div className="section-intro"><div><div className="eyebrow">Why UpForge</div><h2>AI interview practice is now a study skill.</h2></div><p className="lead">A video can teach you a concept. A note can help you revise it. A quiz can expose a gap. An interview simulation forces you to explain it under pressure. UpForge connects all four.</p></div><div className="grid grid4">{careerReasons.map(([a,b],i)=><div className="card feature-card" key={a}><div className="feature-number">0{i+1}</div><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
<section className="section soft"><div className="container"><div className="section-intro"><div><div className="eyebrow">Choose your lane</div><h2>Five career tracks built around real interview skills.</h2></div><p className="lead">AI/ML, full stack, data, cloud/DevOps and cybersecurity are all represented as structured learning paths. Current 2026 developer surveys and hiring reports consistently highlight AI, data, cloud and cybersecurity among important skill areas.</p></div><div className="grid grid5">{tracks.map(t=><Link href={`/track/${t.id}`} className="track-card" key={t.id}><span className="tag">{t.badge}</span><h3>{t.title}</h3><p>{t.desc}</p><div className="skill-row">{t.skills.slice(0,4).map(s=><span key={s}>{s}</span>)}</div><b className="arrow">Explore track →</b></Link>)}</div></div></section>
<section className="section"><div className="container"><div className="split hero-split"><div className="card dark-card"><div className="eyebrow light">The interview room</div><h2>Two technical rounds. Real follow-ups. No canned script.</h2><p>UpForge's AI interview coach asks one question at a time, reacts to your answer and moves from fundamentals into project depth. It is practice — not a hiring decision.</p><div className="round-list"><div><b>Round 1</b><span>Foundations + reasoning</span></div><div><b>Round 2</b><span>Applied + project deep dive</span></div></div><Link className="btn yellow" href="/interview">Open interview room</Link></div><div className="card video-card"><div className="eyebrow">Why videos still matter</div><h2>Learn from people, then test yourself.</h2><p className="lead">We surface established free/open learning libraries rather than pretending UpForge owns the entire internet.</p>{videos.slice(0,3).map(v=><a className="resource-line" href={v.url} target="_blank" rel="noreferrer" key={v.id}><span className="play">▶</span><span><b>{v.title}</b><small>{v.type}</small></span><span>↗</span></a>)}</div></div></div></section>
<section className="section soft"><div className="container pricing-banner"><div><div className="eyebrow">One simple plan</div><h2>Everything you need to prepare, for ₹49.</h2><p className="lead">One personal account, saved progress, learning material, quizzes, curated resources, AI coaching and two technical practice rounds.</p></div><div className="price-box"><div className="price">₹49</div><div className="muted">one-time plan</div><Link className="btn primary" href="/pricing">View plan</Link></div></div></section>
</>}
